name: Deploy to Server

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to server
        run: |
          ssh -t -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd /opt/tennis_project
            git pull origin master
            mv .env.server .env
            #docker compose down
            #docker stop $(docker ps -aq)
            #docker rm $(docker ps -aq)
            #docker rmi $(docker images -q)
            #docker volume rm $(docker volume ls -q)
            #docker network rm $(docker network ls -q | grep -v 'bridge\|host\|none')
            #docker compose up -d --build
          EOF